name = input ("请输入你的名字")
age = input ("请输入你的年龄")
sex = input ("请输入你的性别")
height = input ("请输入你的身高")
weight = input ("请输入你的体重")
hobby = input ("请输入你的爱好")
dizhi = input ("请输入你的家庭住址")
tel = input ("请输入你的电话号码")
print("姓名:%s"%name,"年龄:%s"%age,"性别:%s"%sex,"身高:%s"%height,"体重:%s"%weight,"爱好:%s"%hobby,"家庭住址:%s"%zhuzhi,"电话号码:%s"%tel)

