#房屋大小、房屋面积、城市、详细位置、购房顾问、价格、
dx = input("输入你房屋的大小")
mj = input("输入你房屋的面积")
cs = input("输入你的城市")
xxwz = input("输入你的详细位置")
gw = input("输入你的顾问")
jg = input("输入你的价格")
print("房屋大小:%s"%dx)
print("房屋的面积:%s"%mj)
print("城市:%s"%cs)
print("详细位置:%s"%xxwz)
print("顾问%s"%gw)
print("价格:%s"%jg)
print("欢迎下次光顾")

