#print('*'*25)
name = input ("请输入姓名")
sex = input（"请输入性别"）
tel = input ("请输入电话号码")
adder = input ("请输入电话号码")
email = input ("请输入邮箱地址")
#print("姓名%s\n"%name,"性别%s\n"%sex,"电话%s"%tel,"家庭住址%s"%adder,"邮箱地址%s"%email)
print('*'*25)
print ("姓名%s\n性别%s\n电话%s\n家庭住址%s\n,邮箱地址%s\n"%(name,sex,tel,adder,email,))
print ('*'*25)
